//! Property: the asset token conserves supply, and a self-transfer is a no-op.
//!
//! This is the test that found the self-transfer bug. The old `transfer` wrote
//! `from_balance - amount` and then `from_balance + amount` to the *same* key,
//! so a holder could inflate their own balance arbitrarily while
//! `total_supply` stayed put. A test that only asserted
//! `sum(balances) == total_supply` would *not* have caught it, because
//! `initialize` already violated that law by handing the admin the whole
//! supply while the fan-out mint handed out the same units again — so the
//! target has to check the self-transfer's effect on a single balance
//! directly, not just the aggregate.

use proptest::prelude::*;
use soroban_sdk::{testutils::Address as _, Address, Env, String as SdkString};
use tessera_asset_token::{AssetTokenContract, AssetTokenContractClient, Error as TokenError};
use tessera_compliance::{ComplianceContract, ComplianceContractClient};
use tessera_proptests::{amount, op_sequence, Op};

const HOLDERS: usize = 4;

struct Fixture {
    env: Env,
    token: AssetTokenContractClient<'static>,
    holders: Vec<Address>,
    admin: Address,
}

/// `TryResult` as generated by `#[contractimpl]`.
type Try<T, E> = Result<Result<T, soroban_sdk::ConversionError>, Result<E, soroban_sdk::InvokeError>>;

fn is_ok<T, E>(r: &Try<T, E>) -> bool {
    matches!(r, Ok(Ok(_)))
}

fn is_err<T, E>(r: &Try<T, E>, e: E) -> bool
where
    E: PartialEq + core::fmt::Debug,
{
    matches!(r, Err(Ok(actual)) if *actual == e)
}

fn setup(supply: i128) -> Fixture {
    let env = Env::default();
    let compliance_id = env.register(ComplianceContract, ());
    let token_id = env.register(AssetTokenContract, ());
    let c = ComplianceContractClient::new(&env, &compliance_id).mock_all_auths();

    let admin = Address::generate(&env);
    let mut holders: Vec<Address> = (0..HOLDERS).map(|_| Address::generate(&env)).collect();
    // `initialize` credits the entire supply to the admin, so the admin has to
    // be a tracked participant or the conservation law is wrong from step 0.
    holders[0] = admin.clone();

    c.initialize(&admin);
    for h in &holders {
        c.add_to_allowlist(&admin, h, &SdkString::from_str(&env, "US"), 0);
    }

    let token = AssetTokenContractClient::new(&env, &token_id).mock_all_auths();
    if supply >= 0 {
        let name = SdkString::from_str(&env, "T");
        let r = token.try_initialize(
            &admin, &name, &name, &name, &supply, &6, &compliance_id, &name, &0i128,
        );
        assert!(
            matches!(r, Ok(Ok(_))),
            "setup: initialize failed for supply {supply}: {r:?}"
        );
    }

    Fixture { env, token, holders, admin }
}

fn total_balances(f: &Fixture) -> i128 {
    f.holders
        .iter()
        .fold(0i128, |a, h| a.saturating_add(f.token.balance(h)))
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 96, ..ProptestConfig::default() })]

    /// After any sequence of token operations, the sum of tracked balances is
    /// never below zero and never exceeds the recorded total supply.
    ///
    /// A negative balance is the signature of an underflow that was written
    /// rather than reported; a sum above supply is the signature of units
    /// created out of nothing.
    #[test]
    fn balances_never_exceed_supply(
        supply in 0i128..1_000_000i128,
        ops in op_sequence(HOLDERS, 6),
    ) {
        let f = setup(supply);
        let mut total_supply = supply;
        let mut clawbacked = 0i128;

        for op in &ops {
            match op {
                Op::Transfer { from, to, amount } => {
                    let r = f.token.try_transfer(&f.holders[*from], &f.holders[*to], amount);
                    // A trap here is itself a finding: with `overflow-checks`
                    // on, an overflow panics rather than wrapping.
                    if let Err(Err(soroban_sdk::InvokeError::Abort)) = r {
                        panic!("transfer trapped: {}", op.label());
                    }
                }
                Op::Mint { to, amount } => {
                    let r = f.token.try_mint(&f.admin, &f.holders[*to], amount);
                    if is_ok(&r) {
                        total_supply += amount;
                    } else {
                        prop_assert!(
                            is_err(&r, TokenError::InvalidAmount)
                                || is_err(&r, TokenError::Overflow)
                                || is_err(&r, TokenError::InsufficientBalance),
                            "mint rejected for an unexpected reason: {} -> {r:?}",
                            op.label()
                        );
                    }
                }
                Op::Burn { from, amount } => {
                    let r = f.token.try_burn(&f.holders[*from], amount);
                    if is_ok(&r) {
                        total_supply -= amount;
                    } else {
                        prop_assert!(
                            is_err(&r, TokenError::InvalidAmount)
                                || is_err(&r, TokenError::InsufficientBalance)
                                || is_err(&r, TokenError::Overflow)
                                || is_err(&r, TokenError::Locked),
                            "burn rejected for an unexpected reason: {} -> {r:?}",
                            op.label()
                        );
                    }
                }
                Op::Clawback { from, amount } => {
                    let r = f.token.try_clawback(&f.admin, &f.holders[*from], amount);
                    if is_ok(&r) {
                        // Clawback removes from the holder but deliberately
                        // leaves total supply alone.
                        clawbacked += amount;
                    } else {
                        prop_assert!(
                            is_err(&r, TokenError::InvalidAmount)
                                || is_err(&r, TokenError::InsufficientBalance),
                            "clawback rejected for an unexpected reason: {} -> {r:?}",
                            op.label()
                        );
                    }
                }
            }

            let sum = total_balances(&f);
            prop_assert!(
                sum >= 0,
                "a negative total balance appeared after {}: {sum}",
                op.label()
            );
            prop_assert!(
                sum + clawbacked <= total_supply,
                "balances exceed supply after {}: sum {sum} + clawed {clawbacked} > supply {total_supply}",
                op.label()
            );
        }
    }

    /// A self-transfer of any positive amount leaves the balance untouched.
    ///
    /// This is the direct regression test for the balance-inflation bug. The
    /// `sum <= supply` check above catches it too, but only incidentally; this
    /// one names it.
    #[test]
    fn self_transfer_is_a_no_op(
        supply in 1i128..1_000_000i128,
        holder in 0usize..HOLDERS,
        amount in 1i128..1_000_000i128,
    ) {
        let f = setup(supply);
        let who = &f.holders[holder];
        // Give the holder a balance to work with, so the transfer is not
        // rejected for insufficient balance before it reaches the no-op path.
        let _ = f.token.try_mint(&f.admin, who, &supply);

        let before = f.token.balance(who);
        let r = f.token.try_transfer(who, who, &amount);
        // Whether it is accepted or refused, the balance must not move. The
        // contract returns early for `from == to`, so it is accepted, but the
        // property holds either way and that is what is asserted.
        if is_ok(&r) || is_err(&r, TokenError::InsufficientBalance) {
            prop_assert_eq!(
                f.token.balance(who),
                before,
                "a self-transfer moved the balance ({} units, holder {holder})",
                f.token.balance(who) - before
            );
        }
    }

    /// `mint` is rejected — never wraps — when it would push either the total
    /// supply or a single balance past the `i128` ceiling.
    #[test]
    fn mint_overflow_is_reported_not_wrapped(
        amount in amount().prop_filter("non-trivial", |v| *v > 0),
    ) {
        let f = setup(i128::MAX);
        let r = f.token.try_mint(&f.admin, &f.holders[1], &amount);
        if !is_ok(&r) {
            prop_assert!(
                is_err(&r, TokenError::Overflow) || is_err(&r, TokenError::InvalidAmount),
                "an overflowing mint must report Overflow, got {r:?}"
            );
        }
        // Supply must never have wrapped into a negative number.
        prop_assert_eq!(f.token.total_supply(), i128::MAX);
    }

    /// A non-positive amount is refused by every mutating entry point, and none
    /// of them may trap doing it.
    #[test]
    fn non_positive_amounts_are_refused(
        amount in prop::sample::select(vec![0i128, -1i128, i128::MIN]),
    ) {
        let f = setup(1_000_000);
        for (label, r) in [
            ("transfer", f.token.try_transfer(&f.holders[1], &f.holders[2], &amount)),
            ("burn", f.token.try_burn(&f.holders[1], &amount)),
            ("clawback", f.token.try_clawback(&f.admin, &f.holders[1], &amount)),
            ("mint", f.token.try_mint(&f.admin, &f.holders[1], &amount)),
        ] {
            prop_assert!(!is_ok(&r), "{label} accepted a non-positive amount {amount}");
            prop_assert!(
                is_err(&r, TokenError::InvalidAmount),
                "{label} should report InvalidAmount for {amount}, got {r:?}"
            );
        }
    }

    /// The compliance gate is load-bearing on both sides of a transfer: a
    /// non-allowlisted address can neither receive nor send, and suspending an
    /// allowlisted holder stops it from sending.
    ///
    /// "Load-bearing" is the important word. A token contract that checks
    /// compliance once and then caches the answer, or that only checks the
    /// recipient, would pass a test that only exercises one direction.
    #[test]
    fn compliance_gate_is_load_bearing(
        supply in 10i128..1_000_000i128,
        amount in 1i128..1_000_000i128,
    ) {
        let env = Env::default();
        let compliance_id = env.register(ComplianceContract, ());
        let token_id = env.register(AssetTokenContract, ());
        let c = ComplianceContractClient::new(&env, &compliance_id).mock_all_auths();
        let admin = Address::generate(&env);
        let holder = Address::generate(&env);
        let stranger = Address::generate(&env);
        let name = SdkString::from_str(&env, "T");

        c.initialize(&admin);
        for h in [&admin, &holder] {
            c.add_to_allowlist(&admin, h, &SdkString::from_str(&env, "US"), 0);
        }

        let token = AssetTokenContractClient::new(&env, &token_id).mock_all_auths();
        token.initialize(
            &admin, &name, &name, &name, &supply, &6, &compliance_id, &name, &0i128,
        );
        token.mint(&admin, &holder, &supply);

        // The sender is allowlisted and funded.
        prop_assert!(token.balance(&holder) > 0);

        // A non-allowlisted recipient is refused.
        let into = token.try_transfer(&holder, &stranger, &amount);
        prop_assert!(
            is_err(&into, TokenError::RecipientNotCompliant),
            "a transfer to a non-allowlisted address must be refused, got {into:?}"
        );

        // A non-allowlisted sender is refused, even when the transfer is
        // self-addressed and would otherwise be a no-op. `SenderNotCompliant` is
        // the *only* possible outcome: `transfer` checks the sender's compliance
        // before it reaches the self-transfer no-op, and before the balance
        // check, so neither the no-op nor `InsufficientBalance` can apply here.
        let out = token.try_transfer(&stranger, &stranger, &amount);
        prop_assert!(
            is_err(&out, TokenError::SenderNotCompliant),
            "a transfer from a non-allowlisted address must be refused with \
             SenderNotCompliant, got {out:?}"
        );

        // Suspending the funded, allowlisted holder stops it from sending.
        c.suspend(&admin, &holder);
        let suspended = token.try_transfer(&holder, &admin, &amount);
        prop_assert!(
            is_err(&suspended, TokenError::SenderNotCompliant),
            "a suspended holder must not be able to transfer, got {suspended:?}"
        );
    }
}
